basic.forever(function () {
    basic.showIcon(IconNames.Happy)
    basic.pause(100)
    basic.showIcon(IconNames.Sad)
    basic.pause(100)
    basic.showIcon(IconNames.Confused)
    basic.pause(100)
    basic.showIcon(IconNames.Angry)
    basic.pause(100)
    basic.showIcon(IconNames.Asleep)
})
